name: equatable_macro
description: A Dart library providing a macro for automatic implementation of the Equatable
version: 0.0.1-main.1
repository: https://github.com/antinna/equatable_macro
homepage: https://github.com/antinna/equatable_macro
issue_tracker: https://github.com/antinna/equatable_macro/issues
documentation: https://github.com/antinna/equatable_macro#readme
license: MIT

environment:
  sdk: ^3.5.0-152


dependencies:
  macros: ^0.1.2-main.4
  collection: ^1.19.0
  

dev_dependencies:
  equatable: ^2.0.5
  lints: ^4.0.0
  test: ^1.24.0

screenshots:
  - description: Example output of the @Equatable() macro applied to a class.
    path: screenshots/screenshot1.png
  - description: Demonstration of the @Equatable() macro in use.
    path: screenshots/screenshot2.png
funding:
  - https://github.com/sponsors/Manishmg3994
social:
  github: antinna
  youtube: https://www.youtube.com/@antinna


topics:
  - equatable
  - macros
  - utilities
  - hascode
  - equality
