name: Security Vulnerability Report
description: Use this template to report a security vulnerability.
title: "[Security]: "
labels: [security]
assignees: [manishmg3994]

body:
  - type: markdown
    attributes:
      value: |
        ## Security Vulnerability Report

        Please provide the details of the security vulnerability you have identified below.

  - type: input
    id: vulnerability-description
    attributes:
      label: Describe the vulnerability
      description: A clear and concise description of the vulnerability.
      placeholder: Describe the vulnerability here.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Detailed steps to reproduce the vulnerability.
      placeholder: 1. Step one\n2. Step two\n3. Step three
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Explain what you expected to happen.
      placeholder: Describe the expected behavior here.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: Describe what actually happened.
      placeholder: Describe the actual behavior here.
    validations:
      required: true

  - type: textarea
    id: potential-impact
    attributes:
      label: Potential impact
      description: Explain the potential impact of the vulnerability.
      placeholder: Describe the potential impact here.
    validations:
      required: true

  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested solution or mitigation
      description: Provide suggestions for fixing or mitigating the vulnerability.
      placeholder: Describe your suggested solution or mitigation here.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or information about the vulnerability.
      placeholder: Provide additional context here.
    validations:
      required: false
